---
simulation-params:
  length: 32
  n-fish: 3000
  max-steps: 1000
  delta-t: 0.01
  snapshot-interval: 10
fish-params:
  vel-standard: 1.5
  vel-repulsion: 1.5
  vel-escape: 7.5
  body-length: 1.0
  repulsion-radius: 1.0
  attraction-radius: 7.5
  n-cog: 3
  attraction-strength: 15.0
  attraction-duration: 0.1
